version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.5-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    container_name: tesis-docker-final2
    environment:
      - NEO4J_AUTH=neo4j/Admin12345
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - server.http.listen_address
      - NEO4J_dbms.security.procedures.unrestricted=gds.* 
      - dbms.connector.bolt.listen_address=0.0.0.0:7687
      - dbms.connector.http.enabled=true
      - dbms.connector.https.enabled=true
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins