version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    ports:
       - "27017:27017"
    container_name: mongo-0
    hostname: host-mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    -  MONGO_INITDB_ROOT_PASSWORD=example

    volumes:
      - "./data:/data/db"
      - "./data/log:/var/log/mongodb"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
      #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
 